"""Add password_must_change field

Revision ID: 67bbbce394ed
Revises: 400d2fc5bf0d
Create Date: 2026-01-27 17:24:13.044681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bbbce394ed'
down_revision: Union[str, Sequence[str], None] = '400d2fc5bf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_must_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_must_change')
    # ### end Alembic commands ###
